CREATE SCHEMA IF NOT EXISTS dw;

DROP TABLE IF EXISTS dw.FAT_VCL CASCADE;
DROP TABLE IF EXISTS dw.DIM_MDL CASCADE;
DROP TABLE IF EXISTS dw.DIM_CON CASCADE;
DROP TABLE IF EXISTS dw.DIM_COR CASCADE;

CREATE TABLE dw.DIM_COR (
    SRK_cor BIGSERIAL PRIMARY KEY,
    ext VARCHAR(6),
    itr VARCHAR(6)
);

CREATE TABLE dw.DIM_CON (
    SRK_con BIGSERIAL PRIMARY KEY,
    sel VARCHAR(7),
    cnd VARCHAR(9),
    acc VARCHAR(5)
);

CREATE TABLE dw.DIM_MDL (
    SRK_mdl BIGSERIAL PRIMARY KEY,
    mak VARCHAR(13),
    mod VARCHAR(14),
    yer INTEGER,
    trm VARCHAR(7),
    ehp INTEGER,
    trn VARCHAR(9),
    ful VARCHAR(8),
    drv VARCHAR(3),
    bdy VARCHAR(12)
);

CREATE TABLE dw.FAT_VCL (
    SRK_vcl BIGSERIAL PRIMARY KEY,
    mil INTEGER,
    prc FLOAT,
    own INTEGER,
    age INTEGER,
    mpy FLOAT,
    pop FLOAT,
    
    SRK_mdl BIGINT NOT NULL,
    SRK_con BIGINT NOT NULL,
    SRK_cor BIGINT NOT NULL,
    
    CONSTRAINT SRK_FAT_VCL_mdl
        FOREIGN KEY (SRK_mdl)
        REFERENCES dw.DIM_MDL (SRK_mdl)
        ON DELETE RESTRICT,
    
    CONSTRAINT SRK_FAT_VCL_con
        FOREIGN KEY (SRK_con)
        REFERENCES dw.DIM_CON (SRK_con)
        ON DELETE RESTRICT,
    
    CONSTRAINT SRK_FAT_VCL_cor
        FOREIGN KEY (SRK_cor)
        REFERENCES dw.DIM_COR (SRK_cor)
        ON DELETE RESTRICT
);

CREATE INDEX idx_FAT_VCL_mdl ON dw.FAT_VCL (SRK_mdl);
CREATE INDEX idx_FAT_VCL_con ON dw.FAT_VCL (SRK_con);
CREATE INDEX idx_FAT_VCL_cor ON dw.FAT_VCL (SRK_cor);